apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hapi-fhir-open-emr.fullname" . }}
  labels:
    {{- include "hapi-fhir-open-emr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hapi-fhir-open-emr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hapi-fhir-open-emr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hapi-fhir-open-emr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:      
          - name: openemr.token_url
            valueFrom:
              configMapKeyRef:
                name: openemr-config
                key:  token_url
          - name: openemr.api_url
            valueFrom:
              configMapKeyRef:
                name: openemr-config
                key:  api_url
          - name: openemr.client_id
            valueFrom:
              configMapKeyRef:
                name: openemr-config
                key:  client_id
          - name: openemr.grant_type
            valueFrom:
              configMapKeyRef:
                name: openemr-config
                key:  grant_type
          - name: openemr.user_role
            valueFrom:
              configMapKeyRef:
                name: openemr-config
                key:  user_role
          - name: openemr.scope
            valueFrom:
              configMapKeyRef:
                name: openemr-config
                key:  scope
          - name: openemr.username
            valueFrom:
              secretKeyRef:
                name: openemr-secret
                key:  username
          - name: openemr.password
            valueFrom:
              secretKeyRef:
                name: openemr-secret
                key:  password
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080 
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        
