apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json: 
    '{
      "spring.datasource.url": "{{ .Values.spring.datasource.url }}",
      "spring.datasource.username": "{{ .Values.spring.datasource.username }}",
      "spring.datasource.password": "{{ .Values.spring.datasource.password }}"
    }'