apiVersion: v1
kind: Service
metadata:
  name: {{ include "hapi-fhir-postgres.fullname" . }}
  labels:
    {{- include "hapi-fhir-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: 31201
      name: http
  selector:
    {{- include "hapi-fhir-postgres.selectorLabels" . | nindent 4 }}
