alertmanager:
  enabled: true
grafana:
  enabled: true
  adminPassword: Kms@2021
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - grafana.ohmydev.asia
    paths:
      - /
    tls:
      - secretName: "grafana-ohmydev-asia-tls"
        hosts:
          - "grafana.ohmydev.asia"
prometheus:
  additionalScrapeConfigs:
    - job_name: ingress
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 30s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets:
            - ingress-nginx-controller-metrics.nginx.svc.cluster.local:10254
