alertmanager:
  enabled: true
grafana:
  enabled: true
  adminPassword: Kms@2021
  ingress:
    ingressClassName: "nginx"
    enabled: true
    annotations:
      "cert-manager.io/cluster-issuer": "letsencrypt-prod"
      "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    hosts:
      - grafana.ohmydev.asia
    paths:
      - /
    tls:
      - secretName: "grafana-ohmydev-asia"
        hosts:
          - "grafana.ohmydev.asia"
  additionalDataSources:
    - name: loki-promtail
      basicAuth: false
      editable: false
      jsonData:
        tlsSkipVerify: true
      type: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      version: 1
    - name: ingress-nginx-prometheus
      basicAuth: false
      editable: false
      jsonData:
        tlsSkipVerify: true
      type: prometheus
      url: http://nginx-ingress-prometheus.ingress.svc.cluster.local
      version: 1
  extraScrapeConfigs:
    - job_name: ingress
      honor_timestamps: true
      scrape_interval: 1m
      scrape_timeout: 1m
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets:
            - nginx-ingress-prometheus.ingress.svc.cluster.local
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
