alertmanager:
  enabled: true
grafana:
  enabled: true
  adminPassword: Kms@2021
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - grafana.ohmydev.asia
    paths:
      - /
    tls:
      - secretName: "grafana-ohmydev-asia-tls"
        hosts:
          - "grafana.ohmydev.asia"
  additionalDataSources:
    - name: loki-promtail
      basicAuth: false
      editable: false
      jsonData:
        tlsSkipVerify: true
      type: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      version: 1
