resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 700m
    memory: 1Gi
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: "hapi-fhir.ohmydev.asia"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - host: ["hapi-fhir.ohmydev.asia"]
      secretName: "hapi-fhir-ohmydev-asia-tls"
