resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 700m
    memory: 1Gi
ingress:
  enabled: false
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
  #   kubernetes.io/ingress.class: "nginx"
  #   nginx.ingress.kubernetes.io/ssl-redirect": "true"
  #   ingress.kubernetes.io/rewrite-target": "/"
  # hosts:
  #   - host: "emr.ohmydev.asia"
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls:
  #   - host: ["emr.ohmydev.asia"]
  #     secretName: "emr-ohmydev-asia-tls"
